"""empty message

Revision ID: c7af4f4b9998
Revises: 73a70633e790
Create Date: 2023-04-23 06:17:34.893247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7af4f4b9998'
down_revision = '73a70633e790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_reported')

    # ### end Alembic commands ###
