"""empty message

Revision ID: ed8f35f1e93c
Revises: c7af4f4b9998
Create Date: 2023-04-23 07:04:55.959329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8f35f1e93c'
down_revision = 'c7af4f4b9998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', sa.Boolean(), nullable=True))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('is_reported')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('replys', schema=None) as batch_op:
        batch_op.drop_column('is_reported')

    # ### end Alembic commands ###
